language: node_js
node_js: stable
branches:
  only:
    -master

cache: npm

install: npm install

script: npm run build

deploy:
provider: pages
skip_cleanup: true
github_token: $GH_TOKEN
local_dir: dist
on:
  branch: master